#!/bin/bash

function send-log() {
  CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
  KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
  TIME="10"
  URL="https://api.telegram.org/bot$KEY/sendMessage"
  TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF QUOTA HABIS ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Usage     : </code><code>$total</code>
<code>────────────────────</code>
"
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function con() {
  local -i bytes=$1
  if [[ $bytes -lt 1024 ]]; then
    echo "${bytes} B"
  elif [[ $bytes -lt 1048576 ]]; then
    echo "$(( (bytes + 1023) / 1024 )) KB"
  elif [[ $bytes -lt 1073741824 ]]; then
    echo "$(( (bytes + 1048575) / 1048576 )) MB"
  else
    echo "$(( (bytes + 1073741823) / 1073741824 )) GB"
  fi
}

while true; do
  sleep 30
  data=($(grep '^#!' /etc/trojan/.trojan.db | cut -d ' ' -f 2 | sort | uniq))

  mkdir -p /etc/limit/trojan

  for user in ${data[@]}; do
    xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" > /tmp/${user} 2>/dev/null
    getThis=$(awk '{print $1}' /tmp/${user})

    if [[ ${getThis} != "failed" ]]; then
      downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" | grep -w "value" | awk '{print $2}' | cut -d '"' -f 2)
      user_limit_file="/etc/limit/trojan/${user}"

      if [ -f "$user_limit_file" ]; then
        plus2=$(cat $user_limit_file)
        plus3=$(( ${downlink} + ${plus2} ))
        echo "${plus3}" > $user_limit_file
      else
        echo "${downlink}" > $user_limit_file
      fi

      xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset >/dev/null 2>&1
    fi
  done

  # Check user account limits
  for user in ${data[@]}; do
    if [ -f "/etc/trojan/${user}" ]; then
      checkLimit=$(cat /etc/trojan/${user})

      if [ -n "$checkLimit" ]; then
        if [ -f "/etc/limit/trojan/${user}" ]; then
          Usage=$(cat /etc/limit/trojan/${user})

          if [[ ${Usage} -gt ${checkLimit} ]]; then
            exp=$(grep "^#! $user" /etc/trojan/.trojan.db | awk '{print $3}')
            sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
            sed -i "/^#! $user $exp/d" /etc/trojan/.trojan.db

            total=$(con ${Usage})
            send-log

            rm -f /etc/trojan/$user
            rm -f /etc/kyt/limit/trojan/ip/${user}
            rm -f /etc/limit/trojan/$user
            rm -f /etc/limit/trojan/quota/$user
            rm -f /var/www/html/sodosokws-$user.txt

            systemctl restart xray >/dev/null 2>&1
          fi
        fi
      fi
    fi
  done
done